[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "demoingreadthedocs"
authors = [{name = "Mel"}, {name= 'Kathryn'}]
dynamic = ["version", "description"]
